import type { Boot } from "@/types";

export const boots: Boot[] = [
  {
    id: "nike-mercurial-vapor",
    name: "Nike Mercurial Vapor 16",
    brand: "Nike",
    price: 275,
    rating: 4.8,
    image: "/images/boots/mercurial-vapor.jpg",
    badge: "Best Seller",
  },
  {
    id: "adidas-f50",
    name: "Adidas F50 Elite",
    brand: "Adidas",
    price: 290,
    rating: 4.7,
    image: "/images/boots/adidas-f50.jpg",
    badge: "New",
  },
  {
    id: "puma-future",
    name: "Puma Future 9",
    brand: "Puma",
    price: 230,
    rating: 4.6,
    image: "/images/boots/puma-future.jpg",
  },
  {
    id: "nike-phantom-gx",
    name: "Nike Phantom GX 2",
    brand: "Nike",
    price: 260,
    rating: 4.7,
    image: "/images/boots/phantom-gx.jpg",
  },
  {
    id: "adidas-predator",
    name: "Adidas Predator Elite",
    brand: "Adidas",
    price: 285,
    rating: 4.8,
    image: "/images/boots/adidas-predator.jpg",
    badge: "Limited",
  },
  {
    id: "mizuno-morelia",
    name: "Mizuno Morelia Neo IV",
    brand: "Mizuno",
    price: 310,
    rating: 4.9,
    image: "/images/boots/mizuno-morelia.jpg",
  },
  {
    id: "new-balance-442",
    name: "New Balance 442 V2",
    brand: "New Balance",
    price: 220,
    rating: 4.5,
    image: "/images/boots/new-balance-442.jpg",
  },
  {
    id: "puma-ultra",
    name: "Puma Ultra 5",
    brand: "Puma",
    price: 240,
    rating: 4.4,
    image: "/images/boots/puma-ultra.jpg",
  },
];
